// Auto-generated
let project = new Project('littleGiant');

project.addSources('Sources');
project.addLibrary("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory");
project.addLibrary("C:/MyFiles/ArmorySDK2004/ArmorySDK/iron");
project.addLibrary("C:/MyFiles/ArmorySDK2004/ArmorySDK/lib/haxebullet");
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('arm.MainGame');
project.addParameter("--macro keep('arm.MainGame')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addParameter('arm.MainMenu');
project.addParameter("--macro keep('arm.MainMenu')");
project.addParameter('arm.InitGame');
project.addParameter("--macro keep('arm.InitGame')");
project.addParameter('arm.GenerateGame');
project.addParameter("--macro keep('arm.GenerateGame')");
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addShaders("build_littleGiant/compiled/Shaders/*.glsl", { noembed: false});
project.addShaders("build_littleGiant/compiled/Hlsl/*.glsl", { noprocessing: true, noembed: false });
project.addAssets("build_littleGiant/compiled/Assets/**", { notinlist: true });
project.addAssets("build_littleGiant/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/asteroid.jpg", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/blackhole.jpg", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/dust.jpg", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/gasCloud.jpg", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/largePlanet.png", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/neutronStar.jpg", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/redDwarf.jpg", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/rock.jpg", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/smallPlanet.png", { notinlist: true });
project.addAssets("../textures-Raw/Sourced/superGiant.jpg", { notinlist: true });
project.addAssets("Bundled/Music/BrightGalaxy.wav", { notinlist: true , quality: 0.8999999761581421});
project.addAssets("Bundled/UiAssets/buttonOutline.png", { notinlist: true });
project.addAssets("Bundled/canvas/UI.files", { notinlist: true });
project.addAssets("Bundled/canvas/UI.json", { notinlist: true });
project.addAssets("Bundled/canvas/_themes.json", { notinlist: true });
project.addAssets("Bundled/config.arm", { notinlist: true });
project.addAssets("Bundled/hexagon1.dds", { notinlist: true });
project.addAssets("Bundled/spaceMap.dds", { notinlist: true });
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/smaa_search.png", { notinlist: true });
project.addShaders("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Shaders/debug_draw/**");
project.addParameter('--times');
project.addLibrary("C:/MyFiles/ArmorySDK2004/ArmorySDK/lib/zui");
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('rp_overlays');
project.addDefine('rp_translucency');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_batch');
project.addDefine('arm_stream');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addDefine('arm_config');
project.addDefine('arm_resizable');


resolve(project);
