// Auto-generated
let project = new Project('littleGiant');

project.addSources('Sources');
project.addLibrary("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory");
project.addLibrary("C:/MyFiles/ArmorySDK2004/ArmorySDK/iron");
project.addParameter('arm.MainGame');
project.addParameter("--macro keep('arm.MainGame')");
project.addParameter('arm.GenerateGame');
project.addParameter("--macro keep('arm.GenerateGame')");
project.addParameter('arm.MainMenu');
project.addParameter("--macro keep('arm.MainMenu')");
project.addParameter('armory.trait.internal.LivePatch');
project.addParameter("--macro keep('armory.trait.internal.LivePatch')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('arm.InitGame');
project.addParameter("--macro keep('arm.InitGame')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addShaders("build_littleGiant/compiled/Shaders/*.glsl", { noembed: false});
project.addShaders("build_littleGiant/compiled/Hlsl/*.glsl", { noprocessing: true, noembed: false });
project.addAssets("build_littleGiant/compiled/Assets/**", { notinlist: true });
project.addAssets("build_littleGiant/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("Bundled/Music/BrightGalaxy.wav", { notinlist: true , quality: 0.8999999761581421});
project.addAssets("Bundled/canvas/UI.files", { notinlist: true });
project.addAssets("Bundled/canvas/UI.json", { notinlist: true });
project.addAssets("Bundled/canvas/_themes.json", { notinlist: true });
project.addAssets("Bundled/config.arm", { notinlist: true });
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("ssets/buttonOutline.png", { notinlist: true });
project.addShaders("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Shaders/debug_draw/**");
project.addParameter('--times');
project.addLibrary("C:/MyFiles/ArmorySDK2004/ArmorySDK/lib/zui");
project.addAssets("C:/MyFiles/ArmorySDK2004/ArmorySDK/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_audio');
project.addDefine('arm_patch');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_stream');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addDefine('arm_config');
project.addDefine('arm_resizable');


resolve(project);
